### Add image to an item
PUT  http://localhost:35000/item/addImage
content-type: application/json

{
    "image": "zzz41564156.jpg",
    "Inventory_Number": "55559"
}

### Load item info
GET  http://localhost:35000/item/0/2020
content-type: application/json

### For print barcode or QR code of item
GET  http://localhost:35000/item/forPrintQRcode_Barcode/2020/tanapun@gmail.com
content-type: application/json

### Edit status of item
PUT  http://localhost:35000/item/edit
content-type: application/json

{
    "Status": "7",
    "Inventory_Number": "55559",
    "Email_user": "tanapun@gmail.com"
}

### Load some info of item of landing1
GET  http://localhost:35000/landing1/showSomeInfo
content-type: application/json

### Load all info of item of landing1
GET  http://localhost:35000/landing1/showAllInfo
content-type: application/json

### Load some info of item of landing2
GET  http://localhost:35000/landing2/showSomeInfo
content-type: application/json

### Load item number all in database
GET  http://localhost:35000/item/numberAll
content-type: application/json

### Load item number
GET  http://localhost:35000/item/dashboard/number/2
content-type: application/json

### Load all item info
GET  http://localhost:35000/item/dashboard/showAllInfo
content-type: application/json

### Load inspected item total numbers by a user
GET  http://localhost:35000/user/profile/inspectedItem/Total/Number/tanapun@gmail.com
content-type: application/json

### Load inspected item numbers of status by user
GET  http://localhost:35000/user/profile/inspectedItem/0/tanapun@gmail.com
content-type: application/json

### Load inspected item by the user
GET  http://localhost:35000/user/profile/inspectedInfoItem/tanapun@gmail.com
content-type: application/json

### Load email of user
GET  http://localhost:35000/user/index/info/emailUser/tanapun@gmail.com
content-type: application/json

### Show date and time of job
GET  http://localhost:35000/dateTime/showDateTime
content-type: application/json

### Get information of main datatable page
GET  http://localhost:35000/maindataTable/info/2020/0
content-type: application/json

### Load info of all user of manage user page
GET  http://localhost:35000/manageUser/showAllUser
content-type: application/json

### Edit date // ยังไม่เสร็จ
PUT  http://localhost:35000/dateTime/updateTime/:Date_start/:Date_end
content-type: application/json

{
    "Date_start" : "2020-05-01",
    "Date_end" : "2020-05-30"
    where years = 2020
}